### ISSUE TITLE
cannot pass parameter endpoint by cli

### ISSUE THREAD

**Issue by SeanHH86** [OpenCSGs/csghub-server#67]
1. endpoint can not be use by cli parameter
2. file_download error for repo type of dataset 
```
Traceback (most recent call last):
  File "/Users/hhwang/code/jihulab/opencsg/csghub-sdk/test.py", line 21, in <module>
    result = snapshot_download(repo_id=repoid, cache_dir=cachedir, endpoint=ep, token=my_token, repo_type=repotype)
  File "/Users/hhwang/code/jihulab/opencsg/csghub-sdk/pycsghub/snapshot_download.py", line 61, in snapshot_download
    repo_info = utils.get_repo_info(repo_id,
  File "/Users/hhwang/code/jihulab/opencsg/csghub-sdk/pycsghub/utils.py", line 149, in get_repo_info
    return method(
  File "/Users/hhwang/code/jihulab/opencsg/csghub-sdk/pycsghub/utils.py", line 355, in model_info
    r.raise_for_status()
  File "/Users/hhwang/anaconda3/envs/hubsdk/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://hub-stg.opencsg.com/hf/api/models/wanghh2003/myds1/revision/main
```

**Comment by SeanHH86** [comment]
wrong repo issue
